// saveFiles.js
// require('dotenv').config();
// const Web3 = require("web3");
// const fs = require("fs");
import Web3 from "web3";
import fs from 'fs'
const web3 = new Web3('http://127.0.0.1:7545');
import contractJson from './deployedContract.json' assert {type : 'json'};

const address = contractJson.address;
const abi = contractJson.abi;

// Load deployed contract information (from the file generated by the deploy script)
const contract = new web3.eth.Contract(abi , address);

async function saveFiles(fileEncoding1, fileEncoding2) {
  const accounts = await web3.eth.getAccounts();
  const userAddress = accounts[0]; // Replace with correct user address from Ganache

  try {
    const receipt = await contract.methods.saveFiles(fileEncoding1, fileEncoding2).send({
      from: userAddress,
      gas: 100000
    });
    console.log("Files saved successfully:", receipt);
  } catch (error) {
    console.error("Error saving files:", error);
  }
}

// Call the function with some example data
saveFiles("exampleFileEncoding1", "exampleFileEncoding2");
